[package]
name = "whyslow-common"
version = "0.1.1"
edition.workspace = true
license.workspace = true
description = "Shared event schema for whyslow's eBPF and userspace sides"
repository = "https://github.com/kaorii-ako/whyslow"

[features]
default = []
user = ["aya"]

[dependencies]
aya = { workspace = true, optional = true }

[lib]
path = "src/lib.rs"
